# Generated by Django 6.0.7 on 2026-07-19 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_social', models.CharField(max_length=255)),
                ('profissao', models.CharField(max_length=255)),
                ('endereco', models.TextField()),
                ('contato', models.CharField(max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Profissional da Saúde',
                'verbose_name_plural': 'Profissionais da Saúde',
                'ordering': ['nome_social'],
            },
        ),
    ]
