# Generated by Django 6.0.7 on 2026-07-19 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('professionals', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(fields=('professional', 'data'), name='uk_appointment_professional_data'),
        ),
    ]
